# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\grade\Desktop\studb\ui\dialog_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_about(object):
    def setupUi(self, Dialog_about):
        Dialog_about.setObjectName("Dialog_about")
        Dialog_about.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_about.resize(781, 480)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Dialog_about.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_about)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_about)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog_about)
        QtCore.QMetaObject.connectSlotsByName(Dialog_about)

    def retranslateUi(self, Dialog_about):
        _translate = QtCore.QCoreApplication.translate
        Dialog_about.setWindowTitle(_translate("Dialog_about", "关于"))
        self.label.setText(_translate("Dialog_about", "<html><head/><body><p><span style=\" font-size:16pt;\">学生信息管理系统</span></p><p>版本：暂无版本号</p><p>开源许可证：<a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html\"><span style=\" text-decoration: underline; color:#0000ff;\">GPLv2</span></a></p><p><br/></p><p>本程序旨在提供一种可扩展而统一的办公体验。但是，</p><p>正如你们所见，现在的它还十分粗糙，并不能满足需求。</p><p>所以，您可以帮助我继续开发。或者，您也可以直接对</p><p>作者进行捐赠，我将不胜感激。</p><p><br/></p><p>电子邮件地址：grade6_wty@163.com</p><p>项目主页：<a href=\"https://github.com/wutianyu666/studb\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/wutianyu666/studb</span></a></p><p>门罗币钱包地址：45Ao3gRj4pZaUTYa4AucXtGMH6gCzEznDVM1ZcTwNfyifYYrBp6xDo6Evp1fS1d13sJZgpZuhSLCDMT2EE4Fjtji2hrCtMh</p><p><br/></p></body></html>"))
