# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_new(object):
    def setupUi(self, Dialog_new):
        Dialog_new.setObjectName("Dialog_new")
        Dialog_new.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_new.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Dialog_new.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_new)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_db_title = QtWidgets.QLabel(Dialog_new)
        self.label_db_title.setObjectName("label_db_title")
        self.horizontalLayout.addWidget(self.label_db_title)
        self.lineEdit_db_title = QtWidgets.QLineEdit(Dialog_new)
        self.lineEdit_db_title.setObjectName("lineEdit_db_title")
        self.horizontalLayout.addWidget(self.lineEdit_db_title)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_db_template = QtWidgets.QLabel(Dialog_new)
        self.label_db_template.setObjectName("label_db_template")
        self.horizontalLayout_2.addWidget(self.label_db_template)
        self.pushButton_db_template = QtWidgets.QPushButton(Dialog_new)
        self.pushButton_db_template.setObjectName("pushButton_db_template")
        self.horizontalLayout_2.addWidget(self.pushButton_db_template)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_new)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_new)
        self.buttonBox.rejected.connect(Dialog_new.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_new)

    def retranslateUi(self, Dialog_new):
        _translate = QtCore.QCoreApplication.translate
        Dialog_new.setWindowTitle(_translate("Dialog_new", "新建数据库"))
        self.label_db_title.setText(_translate("Dialog_new", "数据库标题："))
        self.label_db_template.setText(_translate("Dialog_new", "数据库模板："))
        self.pushButton_db_template.setText(_translate("Dialog_new", "选择模板"))
