# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\studb\ui\dialog_delete_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_delete_row(object):
    def setupUi(self, Dialog_delete_row):
        Dialog_delete_row.setObjectName("Dialog_delete_row")
        Dialog_delete_row.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_delete_row.resize(320, 130)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Dialog_delete_row.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_delete_row)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog_delete_row)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(Dialog_delete_row)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_delete_row)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_delete_row)
        self.buttonBox.accepted.connect(Dialog_delete_row.accept)
        self.buttonBox.rejected.connect(Dialog_delete_row.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_delete_row)

    def retranslateUi(self, Dialog_delete_row):
        _translate = QtCore.QCoreApplication.translate
        Dialog_delete_row.setWindowTitle(_translate("Dialog_delete_row", "删除行"))
        self.label.setText(_translate("Dialog_delete_row", "请选择要删除的行号："))
